### ISSUE TITLE
Why fork dbd-modules?

### ISSUE THREAD

**Issue by tdonovan2** [joneschrisan/dbd-modules#1]
I was surprised to see a note on the Apache modules-dev list showing this github repository listed as the location of **dbd-modules** instead of my own  http://sourceforge.net/p/dbd-modules/

Is there a reason you forked the code?  There doesn't appear to be any code changes which warrant a new repository & owner for dbd-modules.

Tom

**Comment by joneschrisan** [comment]
Forked cause I am in the proccess of adding a new module to it. Sorry that this repo has overridden yours on the apache modules-dev list, that was not my intention and not under my control.
